/**
 * Maps UI address form data to database schema fields
 * Handles all the behind-the-scenes field mapping
 */
export const mapUIToDatabase = (uiData, userId, existingId = null) => {
  const now = new Date().toISOString();
  
  return {
    id: existingId || null, // serial auto-generated by DB
    user_id: userId,
    label: uiData.label || ADDRESS_LABELS.HOME,
    address_line1: uiData.flatNumber || '',
    address_line2: [
      uiData.buildingBlock,
      uiData.landmark,
      uiData.areaName
    ].filter(Boolean).join(', '),
    city: uiData.city || '',
    state: uiData.state || '',
    country: uiData.country || 'India', // Default from schema
    pincode: uiData.pincode || '',
    latitude: parseFloat(uiData.latitude) || 0,
    longitude: parseFloat(uiData.longitude) || 0,
    is_primary: uiData.isPrimary || false,
    is_enabled: true,
    is_deleted: false,
    inserted_by: userId?.toString() || 'system',
    inserted_date: existingId ? undefined : now, // Only on create
    modified_date: now,
    // location: geography type - constructed from lat/long by backend
  };
};

/**
 * Maps database fields back to UI format for editing
 */
export const mapDatabaseToUI = (dbData) => {
  const parts = (dbData.address_line2 || '').split(', ');
  
  return {
    id: dbData.id,
    label: dbData.label,
    flatNumber: dbData.address_line1 || '',
    buildingBlock: parts[0] || '',
    landmark: parts[1] || '',
    areaName: parts[2] || '',
    city: dbData.city || '',
    state: dbData.state || '',
    country: dbData.country || '',
    pincode: dbData.pincode || '',
    latitude: dbData.latitude?.toString() || '',
    longitude: dbData.longitude?.toString() || '',
    isPrimary: dbData.is_primary || false,
    receiverName: dbData.receiver_name || '',
    receiverPhone: dbData.receiver_phone || '',
  };
};

/**
 * Formats address for display from DB fields
 */
export const formatAddressDisplay = (dbData) => {
  const parts = [
    dbData.address_line1,
    dbData.address_line2,
    dbData.city,
    dbData.state,
    dbData.pincode
  ].filter(Boolean);
  
  return parts.join(', ');
};